config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  get "/", to: "welcome#home", as: "home"

  get "/transactions/change", to: "transactions#changePosition", as: "change_position"

  resource :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :transactions
  resources :positions
  resources :funds

  resources :users
  # resources :users, only: [ :new, :create, :update, :edit ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :fund
  belongs_to :user
  has_many :transactions, dependent: :nullify
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @positions = Position.where(user_id: params[:id] , status: "ACTIVE")
    @funds = Fund.all
    tickers = @positions.pluck(:ticker).join(", ")
    @stocks = StockQuote::Stock.raw_quote(tickers)
  end

  def show
    @ticker = Position.find(params[:id]).ticker
    @stockData = StockQuote::Stock.chart(@ticker, 'ytd')
  end

  def new
    @position = Position.new
  end

  def edit
  end

  def create
    @position = Position.new(position_params)
    @position.user = User.find(current_user)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_position
    @position = Position.find(params[:id])
  end

  def position_params
    params.require(:position).permit(:ticker, :termination, :user, :fund_id)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.select :all_val,  options %>
  </div>


  <div class="field">
    <%= form.label :user %>
    <% @users = User.all%>
    <% options = options_from_collection_for_select(@users, 'id', 'last_name') %>
    <%= form.select :all_val,  options %>
  </div>



<div>

</div>


  <div class="field">
    <%= form.label :fund_id %>
    <% @funds = Fund.all%>
    <% options = options_from_collection_for_select(@funds, 'id', 'name') %>
    <%= form.select :all_val,  options %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<div class="card">
  <div class="card-header"> View Positions</div>
  <div class="card-body">

    <form action="/positions" method="get">
      <div class="form-group form-inline">
        <label for="exampleInputEmail1">Choose Advisor: &nbsp; </label>
        <select class="form-control" name="id" id="id" onchange="this.form.submit()">
          <% @users = User.all%>

          <% @users.each do |user| %>

          <% if params[:id].to_i == user.id %>
          <option selected="selected" value="<%= user.id %>"><%= user.full_name%></option>
          <% else %>
          <option value="<%= user.id %>"><%= user.full_name%></option>
          <% end %>
          <% end %>
        </select>
      </div>
    </form>
  </div>
</div>


<div class="card">
  <div class="card-header">
    All Positions
  </div>
  <div class="card-body card-table">
    <%= render 'layouts/table' %>
  </div>
  <div class="card-footer" style="text-align: right">
    <%= link_to 'New Trade', new_transaction_path  %>
  </div>
</div>

<% @funds.each do |fund| %>
<% totalBook = 0%>
<% totalMarket = 0%>
<% @positions = fund.positions.where(user_id: params[:id])%>


<% if @positions.length > 0 %>
<div class="card">
  <div class="card-header">
    <a href="/funds/<%=fund.id%>"><%= fund.name %></a>
  </div>
  <div class="card-body card-table">
    <%= render 'layouts/table' %>
  </div>
  <div class="card-footer" style="text-align: right">
    <%= link_to 'New Trade', new_transaction_path  %>
  </div>
</div>
<% end %>
<% end %>

app/views/positions/new.html.erb
<div class="card">
  <div class="card-header">New Trade</div>
  <div class="card-body">
    <form action="/">
      Ticker:
      <input type="text" name="firstname" >
      <input type="submit" value="Search">
    </form>
    <br />
    <br />
    <%= render 'form', position: @position %>
  </div>
</div>

app/views/positions/show.html.erb
<div class="flex-grid">
  <div class="col">
    <div class="card">
      <div class="card-header"> Key details </div>
      <div class="card-body">
        <% @stock = StockQuote::Stock.raw_quote(@position.ticker)[@position.ticker]["quote"] %>
        <strong>Ticker:</strong><%= @stock["symbol"] %> <a
          href="https://finance.yahoo.com/quote/<%=@stock['symbol'] %>/"> (More Details)</a>
        <hr />
        <strong>Company:</strong><%= @stock["companyName"] %>
        <hr />
        <strong>Primary Exchange:</strong><%= @stock["primaryExchange"] %>
        <hr />
        <strong>Position:</strong><%= @position.positionType %>
        <hr />
        <strong>Analyst:</strong><a href="/users/<%= @position.user.id %>"> <%= @position.user.full_name %></a>
        <hr />

        <strong>Fund:</strong>
        <a href="/funds/<%= @position.fund.id%>%"><%= @position.fund.name %></a>
        <hr />

        <strong>Status:</strong>
        <%= @position.status %>

      </div>
    </div>
  </div>

<div class="col">

  <div class="card">
    <div class="card-header"> YTD performance </div>
    <div class="card-body">
      <% data = {}%>
      <% @stockData.chart.each do |day| %>
      <% data[day['date']] = day['close'] %>
      <% end %>
      <%= line_chart data, width: "650px", height: "350px", min: (@stock['close'] * 0.8), discrete: true,  points: false, legend: false  %>
    </div>
  </div>
</div>
</div>

<div class="card">
  <div class="card-header"> Transactions </div>
  <div class="card-body">
    <% @transactions = @position.transactions%>
    <%= render 'layouts/tradesTable' %>
  </div>
</div>