config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  get "/", to: "welcome#home", as: "home"

  get "/transactions/change", to: "transactions#changePosition", as: "change_position"

  resource :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :transactions
  resources :positions
  resources :funds

  resources :users
  # resources :users, only: [ :new, :create, :update, :edit ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :position
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = Stock.all
  end

  def show
  end

  def new
    ticker = params[:ticker].upcase
    stocks = StockQuote::Stock.raw_quote(ticker)

    if stocks.blank?
      render :json => { error: "ticker not found" }
    else
      @stock = Stock.new(
        symbol: stocks[ticker]["quote"]["symbol"],
        companyName: stocks[ticker]["quote"]["companyName"],
        primaryExchange: stocks[ticker]["quote"]["primaryExchange"],
        position: Position.last,
        sector: stocks[ticker]["quote"]["sector"],
        open: stocks[ticker]["quote"]["open"],
        close: stocks[ticker]["quote"]["close"],
        high: stocks[ticker]["quote"]["high"],
        low: stocks[ticker]["quote"]["low"],
        latestPrice: stocks[ticker]["quote"]["latestPrice"],
        latestTime: stocks[ticker]["quote"]["latestTime"],
        latestVolume: stocks[ticker]["quote"]["latestVolume"],
        iexRealTimePrice: stocks[ticker]["quote"]["iexRealTimePrice"],
        previousClose: stocks[ticker]["quote"]["previousClose"],
        changePercent: stocks[ticker]["quote"]["changePercent"],
        iexVolume: stocks[ticker]["quote"]["iexVolume"],
        avgTotalVolume: stocks[ticker]["quote"]["avgTotalVolume"],
        iexBidPrice: stocks[ticker]["quote"]["iexBidPrice"],
        iexBidSize: stocks[ticker]["quote"]["iexBidSize"],
        iexAskPrice: stocks[ticker]["quote"]["iexAskPrice"],
        iexAskSize: stocks[ticker]["quote"]["iexAskSize"],
        marketCap: ((stocks[ticker]["quote"]["marketCap"]).to_i / 1000000),
        peRatio: stocks[ticker]["quote"]["peRatio"],
        week52High: stocks[ticker]["quote"]["week52High"],
        week52Low: stocks[ticker]["quote"]["week52Low"],
        ytdChange: stocks[ticker]["quote"]["ytdChange"],
      )
      render :json => @stock
    end
  end

  def edit
  end

  def create
    @stock = Stock.new(stock_params)
    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_stock
    @stock = Stock.find(params[:id])
  end

  def stock_params
    params.require(:stock).permit(:quote, :companyName, :primaryExchange, :sector, :calculationPrice, :open, :close, :high, :low, :latestPrice, :latestSource, :latestTime, :latestVolume, :iexRealTimePrice, :previousClose, :changePercent, :iexVolume, :avgTotalVolume, :iexBidPrice, :iexBidsize, :iexAskPrice, :iexAskSize, :marketCap, :peRatio, :week52High, :week52Low, :ytdChange, :position_id)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= simple_form_for(@stock) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :quote %>
    <%= f.input :companyName %>
    <%= f.input :primaryExchange %>
    <%= f.input :sector %>
    <%= f.input :calculationPrice %>
    <%= f.input :open %>
    <%= f.input :close %>
    <%= f.input :high %>
    <%= f.input :low %>
    <%= f.input :latestPrice %>
    <%= f.input :latestSource %>
    <%= f.input :latestTime %>
    <%= f.input :latestVolume %>
    <%= f.input :iexRealTimePrice %>
    <%= f.input :previousClose %>
    <%= f.input :changePercent %>
    <%= f.input :iexVolume %>
    <%= f.input :avgTotalVolume %>
    <%= f.input :iexBidPrice %>
    <%= f.input :iexBidsize %>
    <%= f.input :iexAskPrice %>
    <%= f.input :iexAskSize %>
    <%= f.input :marketCap %>
    <%= f.input :peRatio %>
    <%= f.input :week52High %>
    <%= f.input :week52Low %>
    <%= f.input :ytdChange %>
    <%= f.association :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Companyname</th>
      <th>Primaryexchange</th>
      <th>Sector</th>
      <th>Calculationprice</th>
      <th>Open</th>
      <th>Close</th>
      <th>High</th>
      <th>Low</th>
      <th>Latestprice</th>
      <th>Latestsource</th>
      <th>Latesttime</th>
      <th>Latestvolume</th>
      <th>Iexrealtimeprice</th>
      <th>Previousclose</th>
      <th>Changepercent</th>
      <th>Iexvolume</th>
      <th>Avgtotalvolume</th>
      <th>Iexbidprice</th>
      <th>Iexbidsize</th>
      <th>Iexaskprice</th>
      <th>Iexasksize</th>
      <th>Marketcap</th>
      <th>Peratio</th>
      <th>Week52high</th>
      <th>Week52low</th>
      <th>Ytdchange</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.symbol %></td>
        <td><%= stock.companyName %></td>
        <td><%= stock.primaryExchange %></td>
        <td><%= stock.sector %></td>
        <td><%= stock.open %></td>
        <td><%= stock.close %></td>
        <td><%= stock.high %></td>
        <td><%= stock.low %></td>
        <td><%= stock.latestPrice %></td>
        <td><%= stock.latestTime %></td>
        <td><%= stock.latestVolume %></td>
        <td><%= stock.iexRealTimePrice %></td>
        <td><%= stock.previousClose %></td>
        <td><%= stock.changePercent %></td>
        <td><%= stock.iexVolume %></td>
        <td><%= stock.avgTotalVolume %></td>
        <td><%= stock.iexBidPrice %></td>
        <td><%= stock.iexBidSize %></td>
        <td><%= stock.iexAskPrice %></td>
        <td><%= stock.iexAskSize %></td>
        <td><%= stock.marketCap %></td>
        <td><%= stock.peRatio %></td>
        <td><%= stock.week52High %></td>
        <td><%= stock.week52Low %></td>
        <td><%= stock.ytdChange %></td>
        <td><%= stock.position %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @stock.quote %>
</p>

<p>
  <strong>Companyname:</strong>
  <%= @stock.companyName %>
</p>

<p>
  <strong>Primaryexchange:</strong>
  <%= @stock.primaryExchange %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @stock.sector %>
</p>

<p>
  <strong>Calculationprice:</strong>
  <%= @stock.calculationPrice %>
</p>

<p>
  <strong>Open:</strong>
  <%= @stock.open %>
</p>

<p>
  <strong>Close:</strong>
  <%= @stock.close %>
</p>

<p>
  <strong>High:</strong>
  <%= @stock.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @stock.low %>
</p>

<p>
  <strong>Latestprice:</strong>
  <%= @stock.latestPrice %>
</p>

<p>
  <strong>Latestsource:</strong>
  <%= @stock.latestSource %>
</p>

<p>
  <strong>Latesttime:</strong>
  <%= @stock.latestTime %>
</p>

<p>
  <strong>Latestvolume:</strong>
  <%= @stock.latestVolume %>
</p>

<p>
  <strong>Iexrealtimeprice:</strong>
  <%= @stock.iexRealTimePrice %>
</p>

<p>
  <strong>Previousclose:</strong>
  <%= @stock.previousClose %>
</p>

<p>
  <strong>Changepercent:</strong>
  <%= @stock.changePercent %>
</p>

<p>
  <strong>Iexvolume:</strong>
  <%= @stock.iexVolume %>
</p>

<p>
  <strong>Avgtotalvolume:</strong>
  <%= @stock.avgTotalVolume %>
</p>

<p>
  <strong>Iexbidprice:</strong>
  <%= @stock.iexBidPrice %>
</p>

<p>
  <strong>Iexbidsize:</strong>
  <%= @stock.iexBidsize %>
</p>

<p>
  <strong>Iexaskprice:</strong>
  <%= @stock.iexAskPrice %>
</p>

<p>
  <strong>Iexasksize:</strong>
  <%= @stock.iexAskSize %>
</p>

<p>
  <strong>Marketcap:</strong>
  <%= @stock.marketCap %>
</p>

<p>
  <strong>Peratio:</strong>
  <%= @stock.peRatio %>
</p>

<p>
  <strong>Week52high:</strong>
  <%= @stock.week52High %>
</p>

<p>
  <strong>Week52low:</strong>
  <%= @stock.week52Low %>
</p>

<p>
  <strong>Ytdchange:</strong>
  <%= @stock.ytdChange %>
</p>

<p>
  <strong>Position:</strong>
  <%= @stock.position %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>