config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  get "/", to: "welcome#home", as: "home"

  get "/transactions/change", to: "transactions#changePosition", as: "change_position"

  resource :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :transactions
  resources :positions
  resources :funds

  resources :users
  # resources :users, only: [ :new, :create, :update, :edit ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fund.rb
class Fund < ApplicationRecord
  belongs_to :pm, class_name: "User"
  has_many :positions
  has_many :transactions, dependent: :nullify
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:id].to_i > 0
      @fund = Fund.find(params[:id])
    elsif params[:id].to_i == 0
      @funds = Fund.all
    end
  end

  def show
    @fund = Fund.find(params[:id])
    @positions = @fund.positions.where.not(totalShares: 0)
    tickers = @fund.positions.pluck(:ticker).join(", ")
    @stocks = StockQuote::Stock.raw_quote(tickers)
  end

  def new
    @fund = Fund.new
  end

  def edit
  end

  def create
    @fund = Fund.new(fund_params)
    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: "Fund was successfully created." }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: "Fund was successfully updated." }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: "Fund was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_fund
    @fund = Fund.find(params[:id])
  end

  def fund_params
    params.require(:fund).permit(:name, :strategy, :AUM, :inception, :user_id)
  end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_with(model: fund, local: true) do |form| %>
  <% if fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="table">
  <div class="field">
    <%= form.label :name %> <br />
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :strategy %> <br />
    <%= form.text_area :strategy %>
  </div>

  <div class="field">
    <%= form.label :AUM %> <br />
    <%= form.text_field :AUM %>
  </div>

  <div class="field">
    <%= form.label :inception %> <br />
    <%= form.datetime_select :inception %>
  </div>

  <div class="field">
    <%= form.label :PM %> <br />
    <%= form.text_field :user_id %>
  </div>
   <br />

  <div class="actions">
    <%= form.submit %>
  </div>

  </div>
<% end %>

app/views/funds/_table.html.erb
  <table class="table">
      <thead class="thead-dark">
        <tr class="table-header">
          <th  />
          <th >Ticker</th>
          <th>Position</th>
          <th>Company</th>
          <th>Sector</th>
          <th>Entry</th>
          <th>Avg</th>
          <th>Spot</th>
          <th>Shares</th>
          <th>Book</th>
          <th>Market </th>
          <th>PnL</th>
          <th>PnL(%) </th>
          <th>Analyst</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% totalBook = 0%>
        <% totalMarket = 0%>
        <% @positions.each do |position| %>
          <% stock = @stocks[position.ticker]["quote"]%>
          <% bookValue = position.averageCost %>
          <% totalBook += bookValue%>
          <% marketValue = stock["latestPrice"] * position.totalShares.abs %>
          <% totalMarket += marketValue%>
          <tr class="position-row">
            <td class="plus-dropdown" id="<%= position.ticker %>">+</td>
            <td><a href="/positions/<%=position.id%>"> <%= position.ticker %></a></td>
            <td><%= position.positionType%></td>
            <td><%= stock["companyName"].truncate(13) %></td>
            <td><%= position.sector ? position.sector.truncate(13) : "Diversified" %></td>
            <td><%= tableDateFormat(position.created_at) %></td>
            <td><%= number_to_currency(position.averagePrice) %></td>
            <td><%= number_to_currency(stock["latestPrice"]) %></td>
            <td><%= number_with_delimiter(position.totalShares, :delimiter => ',') %> </td>
            <td><%= number_to_currency(bookValue/1000)  %></td>
            <td><%= number_to_currency( marketValue/1000)  %> </td>
            <%
        pnL = position.positionType == "LONG" ? (marketValue - bookValue )/1000 :  (bookValue - marketValue)/1000
        pnLPercent = position.positionType == "LONG" ? (marketValue / bookValue -1) * 100 :  ( bookValue / marketValue -1) * 100 
        
        if (pnL) > 0 
            pnlClass = "positive" 
        else
            pnlClass = "negative" 
        end 
        %>
            <td class="<%= pnlClass %>"><%= number_to_currency(pnL) %></td>
            <td class="<%= pnlClass %>"><%= sprintf("%+.1f", ((pnLPercent).round(1))) %> %</td>
            <td></td>
            <% if position.positionType == "LONG"
            option1 = "BUY"
            option2 = "SELL"
            else
            option1 = "SHORT"
            option2 = "COVER"
            end
          %>
            <td><%= link_to "#{option1}", change_position_path(:id => position.id, :position => position, :type => option1 ) %></td>
            <td><%= link_to "#{option2}", change_position_path(:id => position.id, :position => position, :type => option2 ) %></td>
          </tr>
          <% position.transactions.each do |transaction| %>
            <% tBook = transaction.price * transaction.shares.abs %>
            <% tMarket = stock["latestPrice"] * transaction.shares.abs%>
            <tr class=<%=transaction.ticker %> id="transaction-table">
              <td />
              <td />
              <td />
              <td />
              <td><%= transaction.created_at.strftime("%m/%d/%Y")   %></td>
              <td><%= transaction.tradeType %></td>
              <td><%= number_to_currency(transaction.price) %></td>
              <td />
              <td><%= number_with_delimiter(transaction.shares, :delimiter => ',') %></td>
              <td><%= number_to_currency(tBook/1000) %> </td>
              <td><%= number_to_currency(tMarket/1000) %></td>
              <td><%= number_to_currency( transaction.tradeType == "BUY" ? (tMarket - tBook)/1000 :  (tBook - tMarket)/1000 ) %> </td>
              <td><%= ((((tBook / tMarket)-1) * 100).round(1)) %> %</td>
              <td><a href="/users/<%= position.user.id %>"><%= transaction.user.last_name %></a></td>
            </tr>
          <% end %>
        <% end %>
        <tr >
          <td></td>
          <td>Total</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><%= number_to_currency(totalBook/1000) %></td>
          <td><%= number_to_currency(totalMarket/1000) %></td>
          <td><%= number_to_currency((totalMarket - totalBook)/1000) %></td>
          <td><%= (((totalMarket / totalBook )-1) * 100).round(1) %> %</td>
          <td></td>
          <td colspan="4"></td>
        </tr>
      </tbody>
    </table>

app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/index.html.erb
     <div class="card">
       <div class="card-header">
         View Funds
       </div>

       <div class="card-body">
         <form action="/funds" method="get">
           <div class="form-group form-inline">
             <label for="exampleInputEmail1">Select fund: &nbsp; </label>
             <select width="750px" class="form-control" name="id" id="id" onchange="this.form.submit()">
               <option selected value="0"> All Funds </option>
               <% @fundSelection = Fund.all%>
               <% @fundSelection.each do |fund| %>
               <% if params[:id].to_i == fund.id %>
               <option selected="selected" value="<%= fund.id %>"><%= fund.name%></option>
               <% else %>
               <option value="<%= fund.id %>"><%= fund.name%></option>
               <% end %>
               <% end %>
             </select>
           </div>
         </form>
       </div>
       <div class="card-footer" style="text-align: right">
         <%= link_to 'New Fund', new_fund_path %>
         <% if params["id"].to_i > 0 %>
         <% fund = Fund.find(params["id"]) %> |
         <%= link_to 'Edit Fund', edit_fund_path(fund) %> |
         <%= link_to 'Delete Fund', fund, method: :delete, data: {confirm: 'Are you sure?'} %>
         <% end %>
       </div>
     </div>

     <% if @funds %>
     <% @funds.each do |fund| %>
     <div class="card">
       <div class="card-header">
         <a href="/funds/<%=fund.id%>"><%= fund.name %></a>
       </div>
       <div class="card-body card-table">
         <% @positions = fund.positions.where( status: "ACTIVE") %>
         <% tickers = @positions.pluck(:ticker).join(", ") %>
         <% @stocks = StockQuote::Stock.raw_quote(tickers) %>
         <%= render 'layouts/table' %>
       </div>
       <div class="card-footer" style="text-align:right">
         <%= link_to 'New Trade', new_transaction_path  %>
       </div>
     </div>
     <% end %>
     <% end %>

     <% if @fund %>
     <div class="card">
       <div class="card-header">
         <a href="/funds/<%=@fund.id%>"><%= @fund.name %></a>
       </div>
       <div class="card-body card-table">
         <% @positions = @fund.positions.where( status: "ACTIVE") %>
         <% tickers = @positions.pluck(:ticker).join(", ") %>
         <% @stocks = StockQuote::Stock.raw_quote(tickers) %>
         <%= render 'layouts/table' %>
       </div>
       <div class="card-footer" style="text-align:right">
         <%= link_to 'New Trade', new_transaction_path  %>
       </div>
     </div>
     <% end %>

app/views/funds/new.html.erb
<div class="card">
<div class="card-header">New Fund</div>
<div class="card-body">
<%= render 'form', fund: @fund %>
</div>
</div>

app/views/funds/show.html.erb
    <%

exposures = {}
aum = @positions.sum('averageCost')

@positions.each do |position|
  if exposures.key?(position.sector)
  sum = exposures[position.sector] + position.averageCost.round
  exposures[position.sector] =  sum
  else 
    exposures[position.sector] = position.averageCost.round
  end
end
%>
<div class="card-deck">
  <div class="card">
    <div class="card-header">
      Fund Details
    </div>
    <div class="card-body">
      <p>
        <strong>Name:</strong>
        <%= @fund.name %>
      </p>
      <p>
        <strong>Strategy:</strong>
        <%= @fund.strategy %>
      </p>
      <p>
        <strong>AUM:</strong>
        <%= number_to_currency(aum, precision: 0) %>
      </p>
      <p>
        <strong>Inception:</strong>
        <%= @fund.inception.strftime("%m/%Y") %>
      </p>
      <p>
        <strong>Portfolio Manager:</strong>
        <a href="/users/<%=@fund.pm.id %>"> <%= @fund.pm.first_name + " " + @fund.pm.last_name %> </a>
      </p>
      <p>
        <strong>Active Positions:</strong>
      <%= Position.where(fund_id: @fund.id).size %>
      </p>
    </div>
  </div>
  <div class="card">
    <div class="card-header"> Sector Exposure </div>

      <%= pie_chart exposures , library: { pieSliceText: 'value-and-percentage',  legend: "none" }  %>
  </div>
  <div class="card">
  <div class="card-header">Largest Positions</div>
  <%= bar_chart (@positions.group(:ticker).sum(:averageCost).sort_by{|_key, value| value}).last(10) %>
  <div class="card-body"> </div>
  </div>
</div>

<div class="card">
  <div class="card-header">
Active Positions
  </div>
  <div class="card-body">
    <%= render 'layouts/table' %>
  </div>

  <div class="card-footer" style="text-align: right">
    <%= link_to 'New Trade', new_transaction_path  %>
  </div>
</div>