config/routes.rb
Rails.application.routes.draw do
  resources :stocks

  get "/", to: "welcome#home", as: "home"

  get "/transactions/change", to: "transactions#changePosition", as: "change_position"

  resource :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :transactions
  resources :positions
  resources :funds

  resources :users
  # resources :users, only: [ :new, :create, :update, :edit ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_table.html.erb
  <table class="table">
    <thead class="thead-dark table-header">
      <tr class="table-header">
        <th />
        <th>Fund<br />Exp </th>
        <th>Ticker</th>
        <th>Position</th>
        <th>Avg <br />Price</th>
        <th>Last<br />Price</th>
        <th>Qty <br /> (000's)</th>
        <th>Cost <br /> (000's)</th>
        <th>M2M <br /> (000's) </th>
        <th>PnL <br /> (000's)</th>
        <th>PnL<br />(%) </th>
        <th>Day PnL <br />(000's) </th>
        <th>Day PnL <br /> (%) </th>
        <th>Owner</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>

      <% total = @positions.sum(:averageCost) %>
      <% total_book = 0%>
      <% total_market = 0%>
      <% day_gain_loss = 0%>

      <% @positions.where(status: "ACTIVE").each do |position| %>

        <% stock = @stocks[position.ticker]["quote"]%>
        <% book_value = position.averageCost %>
        <% total_book += book_value%>
        <% market_value = stock["latestPrice"] * position.totalShares.abs %>
        <% total_market += market_value%>
      
        <tr class="position-row">
          <td class="plus-dropdown" id="<%= position.ticker %>">+</td>
          <td> <%= number_to_percentage(book_value/total*100, precision: 1) %> </td>
          <td><a href="/positions/<%=position.id%>"> <%= position.ticker %></a></td>
          <td><%= position.positionType%></td>
          <td><%= number_to_currency(position.averagePrice.abs) %></td>
          <td><%= number_to_currency(stock["latestPrice"]) %></td>
          <td><%= number_with_delimiter(position.totalShares, :delimiter => ',') %> </td>
          <td><%= number_to_currency(book_value/1000, precision: 0)  %></td>
          <td><%= number_to_currency( market_value/1000, precision: 0)  %> </td>
          <% pnL = position.positionType == "LONG" ? (market_value - book_value )/1000 :  (book_value - market_value)/1000 %>
          <% pnLPercent = position.positionType == "LONG" ? (market_value / book_value -1) * 100 :  ( book_value / market_value -1) * 100 %>
          <% pnL > 0 ? pnlClass = "positive" : pnlClass = "negative" %>
          <td class="<%= pnlClass %>"><%= number_to_currency(pnL, precision: 0) %></td>
          <td class="<%= pnlClass %>"><%= percentPnL(pnLPercent)%>%</td>
          <% dayPnL = position.positionType == "LONG" ? (stock['previousClose'] * position.totalShares) * stock['changePercent'] /1000 : (stock['previousClose'] * position.totalShares) * stock['changePercent'] /1000 * -1 %>
          <% dayPnL > 0 ? dayPnLClass = "positive" : dayPnLClass = "negative" %>
          <% day_gain_loss += dayPnL %>
          <td class="<%= dayPnLClass %>"> <%= number_to_currency(dayPnL, precision: 0)%></td>
          <td class="<%= dayPnLClass %>"> <%= percentPnL(stock['changePercent'] * 100)%>%</td>
          <td><a href="/users/<%= position.user.id %>"><%=position.user.last_name %></a></td>
            <% if position.positionType == "LONG"%>
              <% option1 = "BUY" %>
              <% option2 = "SELL" %>
            <% else %>
              <% option1 = "SHORT" %>
              <% option2 = "COVER" %>
            <% end %>
          <td>
            <%= link_to "#{option1}", change_position_path(:id => position.id, :position => position, :type => option1 ) %>
          </td>
          <td>
            <%= link_to "#{option2}", change_position_path(:id => position.id, :position => position, :type => option2 ) %>
          </td>
        </tr>
        <% position.transactions.each do |transaction| %>
          <% tBook = transaction.price * transaction.shares.abs %>
          <% tMarket = stock["latestPrice"] * transaction.shares.abs%>
          <tr class="<%=transaction.ticker%> transaction-details" id="transaction-table">
            <td />
            <td />
            <td />
            <td><%= transaction.tradeType %></td>
            <td><%= number_to_currency(transaction.price) %></td>
            <td><%= number_to_currency(stock['latestPrice']) %></td>
            <td><%= number_with_delimiter(transaction.shares, :delimiter => ',') %></td>
            <td><%= number_to_currency(tBook/1000, precision: 0 ) %> </td>
            <td><%= number_to_currency(tMarket/1000, precision: 0) %></td>
            <% transaction.tradeType == "BUY" ? tPnL = (tMarket - tBook)/1000 : tPnL = (tBook - tMarket)/1000  %>
            <% tPnL > 0 ? tPnLClass = "positive" : tPnLClass = "negative" %>
            <td class="<%=tPnLClass%>">
              <%= number_to_currency( tPnL, precision: 0) %> </td>
            <% transaction.tradeType == "BUY" ? tPercent = ((tMarket / tBook) -1) * 100 : tPercent = ((tBook/tMarket) -1) * 100  %>
            <td class="<%=tPnLClass%>"><%= percentPnL(tPercent) %>%</td>
            <td />
            <td />
            <td><a href="/users/<%= transaction.user.id %>"><%= transaction.user.last_name %></a></td>
            <td />
            <td />
          </tr>
          <% end %>
        <% end %>

      <tr class="row-total">
        <td>Total</td>
        <td>100%</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= number_to_currency(total_book/1000, precision: 0) %></td>
        <td><%= number_to_currency(total_market/1000, precision: 0) %></td>
        <% (total_market - total_book) > 0 ? pnlClass = "positive" : pnlClass = "negative"  %>
        <td class="<%= pnlClass %>"><%= number_to_currency((total_market - total_book)/1000, precision: 0) %></td>
        <td class="<%= pnlClass %>"><%= percentPnL((total_market / total_book -1) *100)  %> %</td>
        <% day_gain_loss > 0 ? pnlClass = "positive" : pnlClass = "negative"  %>
        <td class="<%= pnlClass %>"><%= number_to_currency(day_gain_loss, precision: 0) %></td>
        <td class="<%= pnlClass %>"><%= percentPnL(day_gain_loss/(total_market/1000) * 100) %>%</td>
        <td colspan="4"></td>
      </tr>
    </tbody>
  </table>

app/views/layouts/_tradesTable.html.erb
      <table class="table">
          <thead>
            <tr>
              <th>Ticker </th>
              <th>Fund</th>
              <th>Order </th>
              <th>Entry Date</th>
              <th>Price</th>
              <th>Shares</th>
              <th>Cost</th>
              <th>Investment Reason</th>
              <th>Analyst</th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.order('created_at DESC').each do |transaction| %>
              <tr>
                <td> <a href="/positions/<%= transaction.position.id %>"><%= transaction.ticker %> </a>  </td>
                <td> <a href="/funds/<%=transaction.fund.id %>"> <%= transaction.fund.name %></a></td>
                <td> <%= transaction.tradeType %></td>
                <td> <%= dateFormat(transaction.created_at.localtime) %></td>
                <td><%= number_to_currency(transaction.price) %></td>
                <td><%= commaNumber(transaction.shares) %></td>
                <td><%= number_to_currency(transaction.cost) %></td>
                <td><%= transaction.reason %></td>
                <td> <a href="/users/<%=transaction.user.id %>"> <%= transaction.user.full_name %></a></td>
              </tr>
            <%end%>
          </tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fund Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <a class="navbar-brand" href="/"> <h4><i class="fas fa-coins"></i> Fund Manager </h4></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active"> <%= link_to("Funds", funds_path, :class=>"nav-link")  %> </li>
            <% if current_user%>
            <li class="nav-item active"> <%= link_to("Positions", "/positions/?id=#{current_user.id}", :class=>"nav-link")  %> </li>
            <% else %>
            <li class="nav-item active"> <%= link_to("Positions", "/positions", :class=>"nav-link")  %> </li>
            <% end %>

            <li class="nav-item active"> <%= link_to("New Trade", new_transaction_path, :class=>"nav-link")  %> </li>
            

            <% if current_user%>
            <li class="nav-item active"> <%= link_to("Trade History", transactions_path, :class=>"nav-link")  %> </li>
              <li class="nav-item active"> <%= link_to("Signed in (#{current_user.full_name})", user_path(current_user), :class=>"nav-link") %></li>
              <li class="nav-item active"> <%= link_to("Sign Out", sessions_path, :class=>"nav-link", :method => "delete") %></li>
            <% else %>
              <li class="nav-item active"> <%= link_to("Sign Up", new_user_path, :class=>"nav-link") %></li>
              <li class="nav-item active"> <%= link_to("Sign In", new_sessions_path, :class=>"nav-link") %></li>
            <% end %>
          </ul>
          
          <% if current_user%>
          <form class="form-inline my-2 my-lg-0" action="/transactions/new">
            <input  name="ticker" class="form-control mr-sm-2" size="10" type="search" placeholder="" aria-label="Search">
            <button class="btn btn-outline-secondary type="submit">Trade</button>
          </form>
         <% end %>
        </nav>
        <% flash.each do |type, message| %>
          <div class="alert alert-<%=flash_class(type)%> alert-dismissible fade show">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
      </header>
      <div class="page-contents">
        <%= yield %>
      </div>
    </body>
  </html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<title>Fund Manager</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

/* Full height image header */
.bgimg-1 {
  background-position: center;
  background-size: cover;
  background-image: url("<%= asset_path( 'background2.jpg' ) %>");
  min-height: 100%;
}

.w3-bar .w3-button {
  padding: 16px;
}
</style>
<body>

<!-- Header with full-height image -->
<header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
  <div class="w3-display-left w3-text-white" style="padding:48px">
    <span class="w3-jumbo w3-hide-small">Managing money is never easy.</span><br>
    <span class="w3-large">Gain the edge by tracking positions with Fund Manager </span>
    <p>
    <a href="/users/new" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Sign Up</a>
      <a href="/funds" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Manage Funds</a>
     </p>

  </div> 
  <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
</header>

</body>
</html>